spring:
  application:
    name: Web-Chat-Gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter

        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chats/**
          filters:
            - AuthenticationFilter

        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/ws/**
          filters:
            - WebSocketAuthFilter

      discovery:
        locator:
          enabled: false
          lower-case-service-id: true


server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#    instance:
#      prefer-ip-address: true
#      instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    gateway:
      access: read-only

info:
    app:
    name: Web-Chat-Gateway
    version: "1.0.0"
    description: "A gateway for the Web-Chat application"