spring:
  application:
    name: User-Service
  data:
    mongodb:
      uri: mongodb+srv://softwaredev1112:wRZiT5eHXYEmL0SS@usercluster.rkrue.mongodb.net/?retryWrites=true&w=majority&appName=UserCluster
      database: Users
      auto-index-creation: true
  
server:
  port: 8082

security:
  secret-key: A3F1C2D49B7E8A6F5D4C3B2E1F0A9E8D7C6B5A4F3E2D1C0B9A8F7E6D5C4B3A2F1E0D9C8B7A6F5E4D3C2B1A0F9E8D7C6B5A4F3E2D1C0B9A8F7E6D5C4B3A2F1E0D9C8B7A6
  expiration-time: 86400000

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
